### ISSUE TITLE
remains unknown

### ISSUE THREAD

**Issue by nashshar** [PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring#2]
unknown overnight and in the morning is not reactivated when pv is active and remains unknown

**Comment by preussal** [comment]
i had the same Problem.
I write me a restart / reload Automation



```
alias: Reload GNE integration
description: Reload GNE integration
mode: single
triggers:
  - at: "06:00:00"
    trigger: time
  - at: "07:00:00"
    trigger: time
conditions: []
actions:
  - data:
      entry_id: a0dbfc7de56bce41ee33a9f8c3c917a7
    action: homeassistant.reload_config_entry
```

The config **entry id** is found in **/homeassistant/.config/.storage/core.config_entries** for the one you want to reload.
.config is a hidden Folder. You need to write the hole path in den File editor.
